set -g mouse on
set -g extended-keys on

unbind C-b

set-option -g prefix C-a

bind-key C-a send-prefix



set -g extended-keys-format csi-u

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

# Switch windows with prefix + Ctrl-l / Ctrl-h
bind C-l next-window
bind C-h previous-window

# Switch panes with prefix + h/j/k/l
bind h select-pane -L
bind l select-pane -R
bind j select-pane -D
bind k select-pane -U

# Enter copy (visual) mode with prefix + Enter
bind Enter copy-mode

# Vi mode in copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

# kill session
bind X confirm-before -p "Kill Session #S (y/n)" kill-session

# ── Theme ─────────────────────────────────────────────────────
source-file ~/my-theme/tmux/onyx-gold.tmux.conf
